#!/usr/bin/env bash
# Loops from 1 to 20 and prints "bad luck" messages for superstitious numbers

count=1
while [ $count -le 20 ]
do
  echo $count
  case $count in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  count=$((count + 1))
done
