#!/usr/bin/env bash
# Lists all non-hidden files in the current directory, displaying only the part after the first dash

for file in *; do
  if [[ -f $file || -d $file ]]; then
    echo "${file#*-}"
  fi
done
